---
apiVersion: v1
kind: ConfigMap
metadata:
    name: data-vol
    namespace: default
data:
    index.html: |
        <h1> put contants of a file here </h1>

---
apiVersion: v1
kind: Secret
metadata:
    name: secret-vol
    namespace: default
data:
    token: sfsldjfpojf
