---
apiVersion: v1
kind: Namespace
metadata:
  name: myns
  labels:
    dept: eng
    app: web
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  namespace: myns
  labels:
    app: dov
    tag: v1
spec:
  replicas: 4 #default = 1
  selector:
    matchLabels:
      #Labels that are in the template metadata, to identify which pod belongs to this deployment, We can add one or more label selectors
      app: dov-bear
  template:
    #Everything we wrote for Pods.yml starting from metadata, the rest is understood
    metadata:
      name: dov-bear
      labels:
        app: dov-bear
    spec:
      containers:
        - name: dov-bear-container
          image: chukmunnlee/dov-bear:v1
          #always, (Always pull new from registry, default) ifNotPresent ( Pull only if not present)
          imagePullPolicy: IfNotPresent
          # set environment variables required by the image:
          env:
            - name: PORT
              # env variable can only be string, must be enclosed by ''
              value: '5000'
            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName #Name of the node will be injected here after this pod is created on that node
            - name: INSTANCE_HASH
              valueFrom:
                secretKeyRef:
                  name: dov-secret
                  key: INSTANCE_NAME
          ports:
            - containerPort: 5000
              protocol: 'TCP' #default = tcp


---
apiVersion: v1
kind: Service
metadata:
    name: dov-svc
    namespace: myns
    labels:
        app: dov
spec:
    #ClusterIP is used when the nodes are not exposed outside, NodePort, if you want to expose nodes to each other, LoadBalancer when you want to load balance
    type: ClusterIP
    selector:
        app: dov-bear
    ports:
        - port: 8080
          targetPort: 5000 #this is the container port

