---
apiVersion: v1
kind: Pod
metadata:
  name: dov-bear
  labels:
    app: dov-bear
  namespace: myns
spec:
  containers:
    - name : dov-bear-container
      image: chukmunnlee/dov-bear:v1
      #always, (Always pull new from registry, default) ifNotPresent ( Pull only if not present)
      imagePullPolicy: IfNotPresent
      # set environment variables required by the image:
      env:
        - name: PORT
          # env variable can only be string, must be enclosed by ''
          value: '5000'
        - name : INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName #Name of the node will be injected here after this pod is created on that node
      ports:
        - containerPort: 5000
          protocol: 'TCP' #default = tcp



