#Multi stage build
FROM golang:1.25-bookworm as builder

WORKDIR /src

COPY go.* .
COPY main.go .

RUN go get && go build -o main main.go

# this debian has to be compatible with the above golang image. Both are bookwork in this case.
FROM debian:bookworm
WORKDIR /app

COPY --from=builder /src/main .
COPY public public
COPY templates templates

ENV PORT = 5000
ENV INSTANCE_NAME = dov-bear
EXPOSE ${PORT}

ENTRYPOINT /app/main

